import slugify from "slugify";
import httpStatus from "http-status";

import { prisma } from "../../db/prisma.js";
import ApiError from "../../errors/ApiError.js";

import { buildStartupPrompt } from "../ai/ai.prompt.js";
import { generateStartup } from "../ai/ai.service.js";

import { TGeneratedStartup, TGenerateStartupPayload } from "./startup.interface.js";
import { StartupStatus } from "@prisma/client";
import { GeneratedStartupOutputSchema } from "./startup.validation.js";

const generateUniqueSlug = async (title: string) => {
  const baseSlug = slugify(title, {
    lower: true,
    strict: true,
    trim: true,
  });

  let slug = baseSlug;
  let count = 1;

  while (await prisma.startup.findUnique({ where: { slug } })) {
    slug = `${baseSlug}-${count++}`;
  }

  return slug;
};

const generateStartupIdea = async (payload: TGenerateStartupPayload, userId: string) => {
  const prompt = buildStartupPrompt(payload);

  const aiResult = await generateStartup(prompt);

  const validated = GeneratedStartupOutputSchema.parse(aiResult);

  if (!aiResult.title) {
    throw new ApiError(httpStatus.BAD_REQUEST, "AI failed to generate startup.");
  }

  const slug = await generateUniqueSlug(aiResult.title);

  const startup = await prisma.startup.create({
    data: {
      title: aiResult.title,
      slug,

      idea: payload.idea,
      industry: payload.industry,
      targetAudience: payload.targetAudience,
      budget: payload.budget,
      country: payload.country,

      generatedContent: validated,

      status: StartupStatus.GENERATED,

      userId,
    },
  });

  return startup;
};

const getMyStartups = async (
  userId: string,
  query: {
    search?: string;
    page?: number;
    limit?: number;
    sort?: "asc" | "desc";
  }
) => {
  const page = Number(query.page ?? 1);
  const limit = Number(query.limit ?? 10);
  const skip = (page - 1) * limit;

  const where = {
    userId,
    deletedAt: null,
    ...(query.search && {
      OR: [
        {
          title: {
            contains: query.search,
            mode: "insensitive" as const,
          },
        },
        {
          industry: {
            contains: query.search,
            mode: "insensitive" as const,
          },
        },
      ],
    }),
  };

  const [data, total] = await Promise.all([
    prisma.startup.findMany({
      where,
      skip,
      take: limit,
      orderBy: {
        createdAt: query.sort === "asc" ? "asc" : "desc",
      },
    }),

    prisma.startup.count({
      where,
    }),
  ]);

  return {
    meta: {
      page,
      limit,
      total,
      totalPage: Math.ceil(total / limit),
    },
    data,
  };
};

const getStartupBySlug = async (slug: string, userId: string) => {
  const startup = await prisma.startup.findFirst({
    where: {
      slug,
      userId,
      deletedAt: null,
    },
  });

  if (!startup) {
    throw new ApiError(httpStatus.NOT_FOUND, "Startup not found.");
  }

  return startup;
};

const toggleFavorite = async (id: string, userId: string) => {
  const startup = await prisma.startup.findFirst({
    where: {
      id,
      userId,
      deletedAt: null,
    },
  });

  if (!startup) {
    throw new ApiError(httpStatus.NOT_FOUND, "Startup not found.");
  }

  return prisma.startup.update({
    where: { id },
    data: {
      isFavorite: !startup.isFavorite,
    },
  });
};

const softDeleteStartup = async (id: string, userId: string) => {
  const startup = await prisma.startup.findFirst({
    where: {
      id,
      userId,
      deletedAt: null,
    },
  });

  if (!startup) {
    throw new ApiError(httpStatus.NOT_FOUND, "Startup not found.");
  }

  await prisma.startup.update({
    where: { id },
    data: {
      deletedAt: new Date(),
    },
  });

  return null;
};

const exportStartup = async (id: string, userId: string) => {
  const startup = await prisma.startup.findFirst({
    where: {
      id,
      userId,
      deletedAt: null,
    },
  });

  if (!startup) {
    throw new ApiError(httpStatus.NOT_FOUND, "Startup not found.");
  }

  const content = startup.generatedContent as unknown as TGeneratedStartup;

  const markdown = `# ${startup.title}

## Summary

${content.summary}

---

## Problem

${content.problem}

---

## Solution

${content.solution}

---

## Business Model

${content.businessModel}

---

## Marketing Strategy

${content.marketingStrategy}

---

## MVP Features

${(content.mvpFeatures ?? []).map((item: string) => `- ${item}`).join("\n")}

---

## Tech Stack

${(content.techStack ?? []).map((item: string) => `- ${item}`).join("\n")}

---

## Roadmap

${content.roadmap}

---

Generated by LaunchForge AI
`;

  await prisma.startup.update({
    where: {
      id,
    },
    data: {
      exportedAt: new Date(),
    },
  });

  return {
    filename: `${startup.slug}.md`,
    markdown,
  };
};

const getDashboardStats = async (userId: string) => {
  const [total, favorites, generated, drafts, exported] = await Promise.all([
    prisma.startup.count({
      where: {
        userId,
        deletedAt: null,
      },
    }),

    prisma.startup.count({
      where: {
        userId,
        deletedAt: null,
        isFavorite: true,
      },
    }),

    prisma.startup.count({
      where: {
        userId,
        deletedAt: null,
        status: StartupStatus.GENERATED,
      },
    }),

    prisma.startup.count({
      where: {
        userId,
        deletedAt: null,
        status: StartupStatus.DRAFT,
      },
    }),

    prisma.startup.count({
      where: {
        userId,
        deletedAt: null,
        exportedAt: {
          not: null,
        },
      },
    }),
  ]);

  return {
    total,
    favorites,
    generated,
    drafts,
    exported,
  };
};

export const StartupService = {
  generateStartupIdea,
  getMyStartups,
  getStartupBySlug,
  toggleFavorite,
  softDeleteStartup,
  exportStartup,
  getDashboardStats,
};
